sudo: required
services:
  - docker

before_install:
  - docker build -t manoj/docker-react -f Dockerfile.dev .

script:
  - docker run manoj/docker-react npm run test -- --coverage
 
deploy:
  provider: elasticbeanstalk  
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-866420346258"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET2_KEY"

    